apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ab-test-ingress
  namespace: dev
spec:
  ingressClassName: public
  rules:
  #- host: ab-test.local #if using a DNS - but then you need to change your system host file (remove the dash on the next line)
   - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-a
            port:
              number: 80