apiVersion: v1
kind: Service
metadata:
  name: promotion-server
  namespace: dev
spec:
  selector:
    app: promotion
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000  # Exposing port 5000 on node port 30000 for debugging (external access)
  type: NodePort